### PR TITLE
Fixed audio volume typo

### PR DESCRIPTION
**Pull request by ajmeese7**
Noticed a minor typo when I was combing through the project, nothing too extreme.

### CODE REVIEW

**Comment by andersevenrud** [comment]
Please remove the commit that performs the version bump. This is only done on release, not in patches :)

**Review by andersevenrud — CHANGES_REQUESTED** [review]
Please remove the commit that performs the version bump. This is only done on release, not in patches :)

**Comment by ajmeese7** [comment]
@andersevenrud thanks for the info! The requested change has been made.

**Comment by andersevenrud** [comment]
Thanks!

Just a small tip, create a new branch when you make pull requests. Using the master branch makes it hard to keep in sync with upstream.

**Comment by andersevenrud** [comment]
This was published under a 3.7.3 release tag.

**Pull request merged**
