### PR TITLE
Add support for Persian/Farsi language

### PR DESCRIPTION
**Pull request by msjavan**

### CODE REVIEW

**Comment by msjavan** [comment]
@andersevenrud, I copy & paste the main language file and do changes on it. what should I do for these reviews which are failed?

**Comment by andersevenrud** [comment]
Run `npm run eslint` to see any issues with your javascript

**Comment by msjavan** [comment]
npm run eslint on "/home/morteza/osjs/osjs-client/" output following errors:

/home/morteza/osjs/osjs-client/src/adapters/auth/localstorage.js
  36:27  error  'core' is defined but never used     no-unused-vars
  36:33  error  'options' is defined but never used  no-unused-vars

/home/morteza/osjs/osjs-client/src/adapters/auth/server.js
  36:27  error  'options' is defined but never used  no-unused-vars

/home/morteza/osjs/osjs-client/src/adapters/settings/localstorage.js
  38:30  error  'core' is defined but never used  no-unused-vars

/home/morteza/osjs/osjs-client/src/adapters/ui/iconview.js
  116:14  error  'error' is defined but never used  no-unused-vars
  273:22  error  'files' is defined but never used  no-unused-vars

/home/morteza/osjs/osjs-client/src/adapters/vfs/apps.js
  40:23  error  'options' is defined but never used  no-unused-vars
...
...

What is the problem?

**Comment by andersevenrud** [comment]
I'm not sure why you see all of these messages. There should only be this one as reported here: https://travis-ci.org/os-js/osjs-client/builds/643750230#L247

Have you run `npm install` inside the osjs-client ?

**Comment by msjavan** [comment]
I corrected styling error, what should I do with codeclimate ?

@andersevenrud

**Comment by andersevenrud** [comment]
You can't do anything with the CodeClimate errors. I'm waiting for answer from their support about this issue (i have it in multiple repos).

**Comment by andersevenrud** [comment]
Just in case you make any pull-requests in the future.

Make sure that you create a **new** git branch when you submit these.

In this case I squashed all of your commits so it only looks like **one** was made, meaning that you have to either *reset* your cloned repository to this one, *or* do a new clone.

**Comment by andersevenrud** [comment]
Also, thanks! :)

**Comment by andersevenrud** [comment]
I just published `@osjs/client@3.1.9` with these changes.

**Pull request merged**
