### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by lijunay**
Signed-off-by: lijun_ay <lijunay@gmail.com>

### CODE REVIEW

**Comment by andersevenrud** [comment]
This is great! Thank you :smile: 

I will merge this ASAP.

**Comment by lijunay** [comment]
aha! Serving the people. :smile:

**Comment by andersevenrud** [comment]
Would you mind looking at some other translations as well ?

You can find more information here: https://github.com/os-js/OS.js/issues/18

**Comment by andersevenrud** [comment]
Translations published and included in newly published release. Thanks again :+1:

**Pull request merged**
