### PR TITLE
Add portuguese translation

### PR DESCRIPTION
**Pull request by matheusfelipeog**
I did the osjs-client translation 👍

### CODE REVIEW

**Comment by andersevenrud** [comment]
Great!

Could you also add your new language here so it becomes available for selection ?

https://github.com/os-js/osjs-client/blob/master/src/config.js#L59

**Comment by matheusfelipeog** [comment]
Ops, sorry 😅
I'll adjust

**Comment by andersevenrud** [comment]
Thanks :)

**Comment by matheusfelipeog** [comment]
😁🎉

**Pull request merged**
